[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_q3_video = "8czEAm3gy3uExJKum1zNEYo6gNEV7P9vBTZU3AaXBmND"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbook/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
