[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_q3_video = "2WUo5BgzqJVcYV3Lm8p6g2EGzowW33ArJGRgqBHNUpJL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/macbook/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
